# Generated by Django 5.1.7 on 2025-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
